export const KIN_OUTGOING_MESSAGE_MAX_CHARS = 500;
export const KIN_OUTGOING_MESSAGE_PART_MIN_CHARS = 400;
export const KIN_OUTGOING_MESSAGE_PART_MAX_CHARS = 500;
export const GPT_SYS_MESSAGE_PART_RANGE = "3200-3600";

export const KIN_OUTGOING_MESSAGE_LIMIT_TEXT =
  `keep each message at or under ${KIN_OUTGOING_MESSAGE_MAX_CHARS} characters`;

export const KIN_OUTGOING_MESSAGE_SPLIT_TEXT =
  `split it into ${KIN_OUTGOING_MESSAGE_PART_MIN_CHARS}-${KIN_OUTGOING_MESSAGE_PART_MAX_CHARS} character parts`;
