import type { KinPanelProps } from "@/components/panels/kin/kinPanelTypes";
import type { GptPanelProps } from "@/components/panels/gpt/gptPanelTypes";

export function buildKinPanelProps(args: KinPanelProps): KinPanelProps {
  return args;
}

type BuildGptPanelArgs = Omit<GptPanelProps, "onAnswerTaskRequest"> & {
  pendingRequests: Array<{ id: string; actionId: string; body: string }>;
  buildTaskRequestAnswerDraft: (
    requestId: string,
    requestBody?: string | null
  ) => string;
  setGptInput: (value: string) => void;
};

export function buildGptPanelProps(args: BuildGptPanelArgs): GptPanelProps {
  return {
    ...args,
    header: {
      currentKin: args.currentKin,
      currentKinLabel: args.currentKinLabel,
      kinStatus: args.kinStatus,
      isMobile: args.isMobile,
      onSwitchPanel: args.onSwitchPanel,
    },
    chat: {
      gptState: args.gptState,
      gptMessages: args.gptMessages,
      gptInput: args.gptInput,
      setGptInput: args.setGptInput,
      sendToGpt: args.sendToGpt,
      resetGptForCurrentKin: args.resetGptForCurrentKin,
      loading: args.loading,
      gptBottomRef: args.gptBottomRef,
    },
    task: {
      currentTaskDraft: args.currentTaskDraft,
      taskProgressView: args.taskProgressView,
      pendingInjectionCurrentPart: args.pendingInjectionCurrentPart,
      pendingInjectionTotalParts: args.pendingInjectionTotalParts,
      runPrepTaskFromInput: args.runPrepTaskFromInput,
      runDeepenTaskFromLast: args.runDeepenTaskFromLast,
      runUpdateTaskFromInput: args.runUpdateTaskFromInput,
      runUpdateTaskFromLastGptMessage: args.runUpdateTaskFromLastGptMessage,
      runAttachSearchResultToTask: args.runAttachSearchResultToTask,
      sendLatestGptContentToKin: args.sendLatestGptContentToKin,
      sendCurrentTaskContentToKin: args.sendCurrentTaskContentToKin,
      receiveLastKinResponseToGptInput: args.receiveLastKinResponseToGptInput,
      sendLastGptToKinDraft: args.sendLastGptToKinDraft,
      onChangeTaskTitle: args.onChangeTaskTitle,
      onChangeTaskUserInstruction: args.onChangeTaskUserInstruction,
      onChangeTaskBody: args.onChangeTaskBody,
      onPrepareTaskRequestAck: args.onPrepareTaskRequestAck,
      onPrepareTaskSync: args.onPrepareTaskSync,
      onStartKinTask: args.onStartKinTask,
      onResetTaskContext: args.onResetTaskContext,
    },
    protocol: {
      protocolPrompt: args.protocolPrompt,
      protocolRulebook: args.protocolRulebook,
      pendingIntentCandidates: args.pendingIntentCandidates,
      approvedIntentPhrases: args.approvedIntentPhrases,
      onChangeProtocolPrompt: args.onChangeProtocolPrompt,
      onChangeProtocolRulebook: args.onChangeProtocolRulebook,
      onResetProtocolDefaults: args.onResetProtocolDefaults,
      onSaveProtocolDefaults: args.onSaveProtocolDefaults,
      onSetProtocolRulebookToKinDraft: args.onSetProtocolRulebookToKinDraft,
      onSendProtocolRulebookToKin: args.onSendProtocolRulebookToKin,
      onUpdateIntentCandidate: args.onUpdateIntentCandidate,
      onApproveIntentCandidate: args.onApproveIntentCandidate,
      onRejectIntentCandidate: args.onRejectIntentCandidate,
      onUpdateApprovedIntentPhrase: args.onUpdateApprovedIntentPhrase,
      onDeleteApprovedIntentPhrase: args.onDeleteApprovedIntentPhrase,
    },
    references: {
      lastSearchContext: args.lastSearchContext,
      searchHistory: args.searchHistory,
      selectedTaskSearchResultId: args.selectedTaskSearchResultId,
      multipartAssemblies: args.multipartAssemblies,
      storedDocuments: args.storedDocuments,
      referenceLibraryItems: args.referenceLibraryItems,
      selectedTaskLibraryItemId: args.selectedTaskLibraryItemId,
      onSelectTaskSearchResult: args.onSelectTaskSearchResult,
      onMoveSearchHistoryItem: args.onMoveSearchHistoryItem,
      onDeleteSearchHistoryItem: args.onDeleteSearchHistoryItem,
      onLoadMultipartAssemblyToGptInput: args.onLoadMultipartAssemblyToGptInput,
      onDownloadMultipartAssembly: args.onDownloadMultipartAssembly,
      onDeleteMultipartAssembly: args.onDeleteMultipartAssembly,
      onLoadStoredDocumentToGptInput: args.onLoadStoredDocumentToGptInput,
      onDownloadStoredDocument: args.onDownloadStoredDocument,
      onDeleteStoredDocument: args.onDeleteStoredDocument,
      onMoveStoredDocument: args.onMoveStoredDocument,
      onMoveLibraryItem: args.onMoveLibraryItem,
      onSelectTaskLibraryItem: args.onSelectTaskLibraryItem,
      onChangeLibraryItemMode: args.onChangeLibraryItemMode,
      onStartAskAiModeSearch: args.onStartAskAiModeSearch,
      onSaveStoredDocument: args.onSaveStoredDocument,
    },
    settings: {
      memorySettings: args.memorySettings,
      defaultMemorySettings: args.defaultMemorySettings,
      tokenStats: args.tokenStats,
      responseMode: args.responseMode,
      uploadKind: args.uploadKind,
      ingestMode: args.ingestMode,
      imageDetail: args.imageDetail,
      postIngestAction: args.postIngestAction,
      fileReadPolicy: args.fileReadPolicy,
      compactCharLimit: args.compactCharLimit,
      simpleImageCharLimit: args.simpleImageCharLimit,
      ingestLoading: args.ingestLoading,
      canInjectFile: args.canInjectFile,
      searchMode: args.searchMode,
      searchEngines: args.searchEngines,
      searchLocation: args.searchLocation,
      searchHistoryLimit: args.searchHistoryLimit,
      searchHistoryStorageMB: args.searchHistoryStorageMB,
      autoDocumentReferenceEnabled: args.autoDocumentReferenceEnabled,
      documentReferenceMode: args.documentReferenceMode,
      documentReferenceCount: args.documentReferenceCount,
      documentStorageMB: args.documentStorageMB,
      documentReferenceEstimatedTokens: args.documentReferenceEstimatedTokens,
      autoLibraryReferenceEnabled: args.autoLibraryReferenceEnabled,
      libraryReferenceMode: args.libraryReferenceMode,
      libraryIndexResponseCount: args.libraryIndexResponseCount,
      libraryReferenceCount: args.libraryReferenceCount,
      libraryStorageMB: args.libraryStorageMB,
      libraryReferenceEstimatedTokens: args.libraryReferenceEstimatedTokens,
      autoSendKinSysInput: args.autoSendKinSysInput,
      autoCopyKinSysResponseToGpt: args.autoCopyKinSysResponseToGpt,
      autoSendGptSysInput: args.autoSendGptSysInput,
      autoCopyGptSysResponseToKin: args.autoCopyGptSysResponseToKin,
      onSaveMemorySettings: args.onSaveMemorySettings,
      onResetMemorySettings: args.onResetMemorySettings,
      onChangeResponseMode: args.onChangeResponseMode,
      onChangeUploadKind: args.onChangeUploadKind,
      onChangeIngestMode: args.onChangeIngestMode,
      onChangeImageDetail: args.onChangeImageDetail,
      onChangeCompactCharLimit: args.onChangeCompactCharLimit,
      onChangeSimpleImageCharLimit: args.onChangeSimpleImageCharLimit,
      onChangePostIngestAction: args.onChangePostIngestAction,
      onChangeFileReadPolicy: args.onChangeFileReadPolicy,
      onChangeSearchMode: args.onChangeSearchMode,
      onChangeSearchEngines: args.onChangeSearchEngines,
      onChangeSearchLocation: args.onChangeSearchLocation,
      onChangeSearchHistoryLimit: args.onChangeSearchHistoryLimit,
      onClearSearchHistory: args.onClearSearchHistory,
      onChangeAutoDocumentReferenceEnabled: args.onChangeAutoDocumentReferenceEnabled,
      onChangeDocumentReferenceMode: args.onChangeDocumentReferenceMode,
      onChangeDocumentReferenceCount: args.onChangeDocumentReferenceCount,
      onChangeAutoLibraryReferenceEnabled: args.onChangeAutoLibraryReferenceEnabled,
      onChangeLibraryReferenceMode: args.onChangeLibraryReferenceMode,
      onChangeLibraryIndexResponseCount: args.onChangeLibraryIndexResponseCount,
      onChangeLibraryReferenceCount: args.onChangeLibraryReferenceCount,
      onChangeAutoSendKinSysInput: args.onChangeAutoSendKinSysInput,
      onChangeAutoCopyKinSysResponseToGpt: args.onChangeAutoCopyKinSysResponseToGpt,
      onChangeAutoSendGptSysInput: args.onChangeAutoSendGptSysInput,
      onChangeAutoCopyGptSysResponseToKin: args.onChangeAutoCopyGptSysResponseToKin,
    },
    onAnswerTaskRequest: (requestId) => {
      const request =
        args.pendingRequests.find(
          (item) => item.id === requestId || item.actionId === requestId
        ) || null;
      args.setGptInput(args.buildTaskRequestAnswerDraft(requestId, request?.body));
    },
  };
}
