"use client";

import type {
  ChatPageControllerCompositionArgs,
  ChatPagePanelsViewArgs,
  ChatPageWorkspaceViewArgs,
} from "@/hooks/chatPageCompositionTypes";

export function buildChatPageWorkspaceControllerArgs(
  args: ChatPageWorkspaceViewArgs
): ChatPageControllerCompositionArgs {
  return {
    app: {
      currentKin: args.app.currentKin,
      kinList: args.app.kinList,
      isMobile: args.app.isMobile,
      setActiveTab: args.app.setActiveTab,
      setKinConnectionState: args.app.setKinConnectionState,
    },
    uiState: {
      gptInput: args.ui.gptInput,
      kinInput: args.ui.kinInput,
      gptLoading: args.ui.gptLoading,
      kinLoading: args.ui.kinLoading,
      ingestLoading: args.ui.ingestLoading,
      gptMessages: args.ui.gptMessages,
      kinMessages: args.ui.kinMessages,
      pendingKinInjectionBlocks: args.ui.pendingKinInjectionBlocks,
      pendingKinInjectionIndex: args.ui.pendingKinInjectionIndex,
      setKinInput: args.ui.setKinInput,
      setGptInput: args.ui.setGptInput,
      setKinMessages: args.ui.setKinMessages,
      setGptMessages: args.ui.setGptMessages,
      setKinLoading: args.ui.setKinLoading,
      setGptLoading: args.ui.setGptLoading,
      setIngestLoading: args.ui.setIngestLoading,
      setPendingKinInjectionBlocks: args.ui.setPendingKinInjectionBlocks,
      setPendingKinInjectionIndex: args.ui.setPendingKinInjectionIndex,
    },
    task: {
      currentTaskDraft: args.task.currentTaskDraft,
      setCurrentTaskDraft: args.task.setCurrentTaskDraft,
      getTaskBaseText: args.task.getTaskBaseText,
      getTaskLibraryItem: args.task.getTaskLibraryItem,
      getResolvedTaskTitle: args.task.getResolvedTaskTitle,
      resolveTaskTitleFromDraft: args.task.resolveTaskTitleFromDraft,
      getTaskSlotLabel: args.task.getTaskSlotLabel,
      syncTaskDraftFromProtocol: args.task.syncTaskDraftFromProtocol,
      applyPrefixedTaskFieldsFromText: args.task.applyPrefixedTaskFieldsFromText,
      getCurrentTaskCharConstraint: args.task.getCurrentTaskCharConstraint,
      resetCurrentTaskDraft: args.task.resetCurrentTaskDraft,
      taskProtocol: args.task.taskProtocol,
      taskProtocolView: args.task.taskProtocolView,
    },
    protocol: {
      approvedIntentPhrases: args.protocol.approvedIntentPhrases,
      rejectedIntentCandidateSignatures:
        args.protocol.rejectedIntentCandidateSignatures,
      pendingIntentCandidates: args.protocol.pendingIntentCandidates,
      protocolPrompt: args.protocol.protocolPrompt,
      protocolRulebook: args.protocol.protocolRulebook,
      chatBridgeSettings: args.protocol.chatBridgeSettings,
      setPendingIntentCandidates: args.protocol.setPendingIntentCandidates,
      setApprovedIntentPhrases: args.protocol.setApprovedIntentPhrases,
      setRejectedIntentCandidateSignatures:
        args.protocol.setRejectedIntentCandidateSignatures,
      setProtocolPrompt: args.protocol.setProtocolPrompt,
      setProtocolRulebook: args.protocol.setProtocolRulebook,
      promptDefaultKey: args.protocol.promptDefaultKey,
      rulebookDefaultKey: args.protocol.rulebookDefaultKey,
    },
    search: {
      lastSearchContext: args.search.lastSearchContext,
      searchMode: args.search.searchMode,
      searchEngines: args.search.searchEngines,
      searchLocation: args.search.searchLocation,
      processMultipartTaskDoneText: args.search.processMultipartTaskDoneText,
      recordSearchContext: args.search.recordSearchContext,
      getContinuationTokenForSeries: args.search.getContinuationTokenForSeries,
      getAskAiModeLinkForQuery: args.search.getAskAiModeLinkForQuery,
      clearSearchHistory: args.search.clearSearchHistory,
      deleteSearchHistoryItemBase: args.search.deleteSearchHistoryItemBase,
    },
    services: {
      responseMode: args.gpt.responseMode,
      autoCopyFileIngestSysInfoToKin:
        args.bridge.autoBridgeSettings.autoCopyFileIngestSysInfoToKin,
      gptMemoryRuntime: args.gpt.gptMemoryRuntime,
      setUploadKind: args.gpt.onChangeUploadKind,
      applySearchUsage: args.usage.applySearchUsage,
      applyChatUsage: args.usage.applyChatUsage,
      applySummaryUsage: args.usage.applySummaryUsage,
      applyTaskUsage: args.usage.applyTaskUsage,
      applyIngestUsage: args.usage.applyIngestUsage,
      buildLibraryReferenceContext: args.references.buildLibraryReferenceContext,
      referenceLibraryItems: args.references.referenceLibraryItems,
      libraryIndexResponseCount: args.references.libraryIndexResponseCount,
      recordIngestedDocument: args.usage.recordIngestedDocument,
      gptMemorySettingsControls: args.gpt.gptMemorySettingsControls,
      ingestProtocolMessage: args.task.taskProtocolView.ingestProtocolMessage,
    },
    automation: {
      autoBridgeSettings: args.bridge.autoBridgeSettings,
      kinInput: args.ui.kinInput,
      gptInput: args.ui.gptInput,
      kinLoading: args.ui.kinLoading,
      gptLoading: args.ui.gptLoading,
      kinMessages: args.ui.kinMessages,
      gptMessages: args.ui.gptMessages,
      setGptInput: args.ui.setGptInput,
      setKinInput: args.ui.setKinInput,
      isMobile: args.app.isMobile,
      setActiveTab: args.app.setActiveTab,
    },
    reset: {
      setKinMessages: args.ui.setKinMessages,
      setGptMessages: args.ui.setGptMessages,
      resetTokenStats: args.reset.resetTokenStats,
      resetCurrentTaskDraft: args.task.resetCurrentTaskDraft,
      isMobile: args.app.isMobile,
      setActiveTab: args.app.setActiveTab,
      connectKin: args.reset.connectKin,
      switchKin: args.reset.switchKin,
      disconnectKin: args.reset.disconnectKin,
      removeKinState: args.reset.removeKinState,
      removeKin: args.reset.removeKin,
      resetGptForCurrentKin: args.gpt.resetGptForCurrentKin,
    },
  };
}

export function buildChatPageWorkspacePanelsViewArgs(
  args: ChatPageWorkspaceViewArgs
): ChatPagePanelsViewArgs {
  return {
    controller: buildChatPageWorkspaceControllerArgs(args),
    panelApp: {
      currentKin: args.app.currentKin,
      currentKinLabel: args.app.currentKinLabel,
      kinStatus: args.app.kinStatus,
      kinList: args.app.kinList,
      isMobile: args.app.isMobile,
    },
    taskProtocolView: args.task.taskProtocolView,
    kinPanel: {
      activeTabSetter: () => args.app.setActiveTab("gpt"),
      kinState: {
        kinIdInput: args.kin.kinIdInput,
        setKinIdInput: args.kin.setKinIdInput,
        kinNameInput: args.kin.kinNameInput,
        setKinNameInput: args.kin.setKinNameInput,
        currentKin: args.app.currentKin,
        kinMessages: args.ui.kinMessages,
        kinInput: args.ui.kinInput,
        setKinInput: args.ui.setKinInput,
        renameKin: args.kin.renameKin,
        kinBottomRef: args.ui.kinBottomRef,
        loading: args.ui.kinLoading,
        pendingInjectionBlocks: args.ui.pendingKinInjectionBlocks,
        pendingInjectionIndex: args.ui.pendingKinInjectionIndex,
      },
    },
    gptPanel: {
      activeTabSetter: () => args.app.setActiveTab("kin"),
      pendingInjection: {
        blocks: args.ui.pendingKinInjectionBlocks,
        index: args.ui.pendingKinInjectionIndex,
      },
      gptState: {
        gptState: args.gpt.gptState,
        gptMessages: args.ui.gptMessages,
        gptInput: args.ui.gptInput,
        setGptInput: args.ui.setGptInput,
        gptBottomRef: args.ui.gptBottomRef,
        loading: args.ui.gptLoading,
        ingestLoading: args.ui.ingestLoading,
      },
      task: {
        currentTaskDraft: args.task.currentTaskDraft,
        taskDraftCount: args.task.taskDraftCount,
        activeTaskDraftIndex: args.task.activeTaskDraftIndex,
        resetCurrentTaskDraft: args.task.resetCurrentTaskDraft,
        updateTaskDraftFields: args.task.updateTaskDraftFields,
        pendingRequests: args.task.taskProtocolView.pendingRequests,
        buildTaskRequestAnswerDraft: args.task.buildTaskRequestAnswerDraft,
        onSelectPreviousTaskDraft: args.task.onSelectPreviousTaskDraft,
        onSelectNextTaskDraft: args.task.onSelectNextTaskDraft,
      },
      references: {
        lastSearchContext: args.search.lastSearchContext,
        searchHistory: args.search.searchHistory,
        selectedTaskSearchResultId: args.search.selectedTaskSearchResultId,
        multipartAssemblies: args.references.multipartAssemblies,
        storedDocuments: args.references.storedDocuments,
        referenceLibraryItems: args.references.referenceLibraryItems,
        selectedTaskLibraryItemId: args.references.selectedTaskLibraryItemId,
        onSelectTaskSearchResult: args.search.onSelectTaskSearchResult,
        onMoveSearchHistoryItem: args.search.onMoveSearchHistoryItem,
        onDeleteSearchHistoryItem: args.search.onDeleteSearchHistoryItem,
        onLoadMultipartAssemblyToGptInput:
          args.references.onLoadMultipartAssemblyToGptInput,
        onDownloadMultipartAssembly: args.references.onDownloadMultipartAssembly,
        onDeleteMultipartAssembly: args.references.onDeleteMultipartAssembly,
        onLoadStoredDocumentToGptInput:
          args.references.onLoadStoredDocumentToGptInput,
        onDownloadStoredDocument: args.references.onDownloadStoredDocument,
        onDeleteStoredDocument: args.references.onDeleteStoredDocument,
        onMoveStoredDocument: args.references.onMoveStoredDocument,
        onMoveLibraryItem: args.references.onMoveLibraryItem,
        onSelectTaskLibraryItem: args.references.onSelectTaskLibraryItem,
        onChangeLibraryItemMode: args.references.onChangeLibraryItemMode,
        onSaveStoredDocument: args.references.onSaveStoredDocument,
      },
      settings: {
        memorySettings: args.memory.memorySettings,
        defaultMemorySettings: args.gpt.defaultMemorySettings,
        tokenStats: args.memory.tokenStats,
        responseMode: args.gpt.responseMode,
        uploadKind: args.gpt.uploadKind,
        ingestMode: args.gpt.ingestMode,
        imageDetail: args.gpt.imageDetail,
        postIngestAction: args.gpt.postIngestAction,
        fileReadPolicy: args.gpt.fileReadPolicy,
        compactCharLimit: args.gpt.compactCharLimit,
        simpleImageCharLimit: args.gpt.simpleImageCharLimit,
        ingestLoading: args.ui.ingestLoading,
        canInjectFile: !args.ui.gptLoading && !args.ui.ingestLoading,
        searchMode: args.search.searchMode,
        searchEngines: args.search.searchEngines,
        searchLocation: args.search.searchLocation,
        sourceDisplayCount: args.search.sourceDisplayCount,
        autoLibraryReferenceEnabled: args.references.autoLibraryReferenceEnabled,
        libraryReferenceMode: args.references.libraryReferenceMode,
        libraryIndexResponseCount: args.references.libraryIndexResponseCount,
        libraryReferenceCount: args.references.libraryReferenceCount,
        libraryStorageMB: args.references.libraryStorageMB,
        libraryReferenceEstimatedTokens:
          args.references.libraryReferenceEstimatedTokens,
        autoSendKinSysInput: args.bridge.autoBridgeSettings.autoSendKinSysInput,
        autoCopyKinSysResponseToGpt:
          args.bridge.autoBridgeSettings.autoCopyKinSysResponseToGpt,
        autoSendGptSysInput: args.bridge.autoBridgeSettings.autoSendGptSysInput,
        autoCopyGptSysResponseToKin:
          args.bridge.autoBridgeSettings.autoCopyGptSysResponseToKin,
        autoCopyFileIngestSysInfoToKin:
          args.bridge.autoBridgeSettings.autoCopyFileIngestSysInfoToKin,
        onChangeResponseMode: args.gpt.onChangeResponseMode,
        onChangeUploadKind: args.gpt.onChangeUploadKind,
        onChangeIngestMode: args.gpt.onChangeIngestMode,
        onChangeImageDetail: args.gpt.onChangeImageDetail,
        onChangeCompactCharLimit: args.gpt.onChangeCompactCharLimit,
        onChangeSimpleImageCharLimit: args.gpt.onChangeSimpleImageCharLimit,
        onChangePostIngestAction: args.gpt.onChangePostIngestAction,
        onChangeFileReadPolicy: args.gpt.onChangeFileReadPolicy,
        onChangeSearchMode: args.search.onChangeSearchMode,
        onChangeSearchEngines: args.search.onChangeSearchEngines,
        onChangeSearchLocation: args.search.onChangeSearchLocation,
        onChangeSourceDisplayCount: args.search.onChangeSourceDisplayCount,
        onChangeAutoLibraryReferenceEnabled:
          args.references.onChangeAutoLibraryReferenceEnabled,
        onChangeLibraryReferenceMode:
          args.references.onChangeLibraryReferenceMode,
        onChangeLibraryIndexResponseCount:
          args.references.onChangeLibraryIndexResponseCount,
        onChangeLibraryReferenceCount:
          args.references.onChangeLibraryReferenceCount,
        onChangeAutoSendKinSysInput: args.bridge.onChangeAutoSendKinSysInput,
        onChangeAutoCopyKinSysResponseToGpt:
          args.bridge.onChangeAutoCopyKinSysResponseToGpt,
        onChangeAutoSendGptSysInput: args.bridge.onChangeAutoSendGptSysInput,
        onChangeAutoCopyGptSysResponseToKin:
          args.bridge.onChangeAutoCopyGptSysResponseToKin,
        onChangeAutoCopyFileIngestSysInfoToKin:
          args.bridge.onChangeAutoCopyFileIngestSysInfoToKin,
        onChangeMemoryInterpreterSettings:
          args.memory.onChangeMemoryInterpreterSettings,
      },
      protocolState: {
        protocolPrompt: args.protocol.protocolPrompt,
        protocolRulebook: args.protocol.protocolRulebook,
        pendingIntentCandidates: args.protocol.pendingIntentCandidates,
        approvedIntentPhrases: args.protocol.approvedIntentPhrases,
        onChangeProtocolPrompt: args.protocol.onChangeProtocolPrompt,
        onChangeProtocolRulebook: args.protocol.onChangeProtocolRulebook,
      },
      memoryState: {
        memoryInterpreterSettings: args.memory.memoryInterpreterSettings,
        pendingMemoryRuleCandidates: args.memory.pendingMemoryRuleCandidates,
        approvedMemoryRules: args.memory.approvedMemoryRules,
        onApproveMemoryRuleCandidate: args.memory.onApproveMemoryRuleCandidate,
        onRejectMemoryRuleCandidate: args.memory.onRejectMemoryRuleCandidate,
        onUpdateMemoryRuleCandidate: args.memory.onUpdateMemoryRuleCandidate,
        onDeleteApprovedMemoryRule: args.memory.onDeleteApprovedMemoryRule,
      },
    },
    taskSnapshot: {
      currentTaskDraft: args.task.currentTaskDraft,
      recordIngestedDocument: args.usage.recordIngestedDocument,
    },
  };
}
