import type { ChatPageControllerServicesSectionArgs } from "@/hooks/chatPageControllerCompositionTypes";
import type { ChatPageGptPanelCompositionArgs } from "@/hooks/chatPagePanelArgsTypes";

export type ChatPageWorkspaceViewReferencesArgs = {
  multipartAssemblies: ChatPageGptPanelCompositionArgs["references"]["multipartAssemblies"];
  storedDocuments: ChatPageGptPanelCompositionArgs["references"]["storedDocuments"];
  referenceLibraryItems:
    ChatPageGptPanelCompositionArgs["references"]["referenceLibraryItems"];
  libraryRagIndexStates:
    ChatPageGptPanelCompositionArgs["references"]["libraryRagIndexStates"];
  selectedTaskLibraryItemId:
    ChatPageGptPanelCompositionArgs["references"]["selectedTaskLibraryItemId"];
  onDeleteMultipartAssembly:
    ChatPageGptPanelCompositionArgs["references"]["onDeleteMultipartAssembly"];
  onLoadMultipartAssemblyToGptInput:
    ChatPageGptPanelCompositionArgs["references"]["onLoadMultipartAssemblyToGptInput"];
  onDownloadMultipartAssembly:
    ChatPageGptPanelCompositionArgs["references"]["onDownloadMultipartAssembly"];
  onLoadStoredDocumentToGptInput:
    ChatPageGptPanelCompositionArgs["references"]["onLoadStoredDocumentToGptInput"];
  onDownloadStoredDocument:
    ChatPageGptPanelCompositionArgs["references"]["onDownloadStoredDocument"];
  onDeleteStoredDocument:
    ChatPageGptPanelCompositionArgs["references"]["onDeleteStoredDocument"];
  onMoveStoredDocument:
    ChatPageGptPanelCompositionArgs["references"]["onMoveStoredDocument"];
  onMoveLibraryItem:
    ChatPageGptPanelCompositionArgs["references"]["onMoveLibraryItem"];
  onSelectTaskLibraryItem:
    ChatPageGptPanelCompositionArgs["references"]["onSelectTaskLibraryItem"];
  onChangeLibraryItemMode:
    ChatPageGptPanelCompositionArgs["references"]["onChangeLibraryItemMode"];
  onIndexLibraryItemForRag:
    ChatPageGptPanelCompositionArgs["references"]["onIndexLibraryItemForRag"];
  onSaveStoredDocument:
    ChatPageGptPanelCompositionArgs["references"]["onSaveStoredDocument"];
  buildLibraryReferenceContext:
    ChatPageControllerServicesSectionArgs["buildLibraryReferenceContext"];
  buildLibraryReferenceContextForQuery:
    ChatPageControllerServicesSectionArgs["buildLibraryReferenceContextForQuery"];
  applyRegisteredTaskRuntimeSettings:
    ChatPageControllerServicesSectionArgs["applyRegisteredTaskRuntimeSettings"];
  autoLibraryReferenceEnabled:
    ChatPageGptPanelCompositionArgs["settings"]["autoLibraryReferenceEnabled"];
  onChangeAutoLibraryReferenceEnabled:
    ChatPageGptPanelCompositionArgs["settings"]["onChangeAutoLibraryReferenceEnabled"];
  libraryReferenceMode:
    ChatPageGptPanelCompositionArgs["settings"]["libraryReferenceMode"];
  onChangeLibraryReferenceMode:
    ChatPageGptPanelCompositionArgs["settings"]["onChangeLibraryReferenceMode"];
  libraryIndexResponseCount:
    ChatPageGptPanelCompositionArgs["settings"]["libraryIndexResponseCount"];
  onChangeLibraryIndexResponseCount:
    ChatPageGptPanelCompositionArgs["settings"]["onChangeLibraryIndexResponseCount"];
  libraryReferenceCount:
    ChatPageGptPanelCompositionArgs["settings"]["libraryReferenceCount"];
  libraryRagReferenceEnabled:
    ChatPageGptPanelCompositionArgs["settings"]["libraryRagReferenceEnabled"];
  onChangeLibraryRagReferenceEnabled:
    ChatPageGptPanelCompositionArgs["settings"]["onChangeLibraryRagReferenceEnabled"];
  libraryRagReferenceCount:
    ChatPageGptPanelCompositionArgs["settings"]["libraryRagReferenceCount"];
  onChangeLibraryRagReferenceCount:
    ChatPageGptPanelCompositionArgs["settings"]["onChangeLibraryRagReferenceCount"];
  libraryRagCandidateCount:
    ChatPageGptPanelCompositionArgs["settings"]["libraryRagCandidateCount"];
  onChangeLibraryRagCandidateCount:
    ChatPageGptPanelCompositionArgs["settings"]["onChangeLibraryRagCandidateCount"];
  libraryRagSimilarityThreshold:
    ChatPageGptPanelCompositionArgs["settings"]["libraryRagSimilarityThreshold"];
  onChangeLibraryRagSimilarityThreshold:
    ChatPageGptPanelCompositionArgs["settings"]["onChangeLibraryRagSimilarityThreshold"];
  imageLibraryReferenceEnabled:
    ChatPageGptPanelCompositionArgs["settings"]["imageLibraryReferenceEnabled"];
  onChangeImageLibraryReferenceEnabled:
    ChatPageGptPanelCompositionArgs["settings"]["onChangeImageLibraryReferenceEnabled"];
  imageLibraryReferenceCount:
    ChatPageGptPanelCompositionArgs["settings"]["imageLibraryReferenceCount"];
  onChangeImageLibraryReferenceCount:
    ChatPageGptPanelCompositionArgs["settings"]["onChangeImageLibraryReferenceCount"];
  imageLibraryCardLimit:
    ChatPageGptPanelCompositionArgs["settings"]["imageLibraryCardLimit"];
  onChangeImageLibraryCardLimit:
    ChatPageGptPanelCompositionArgs["settings"]["onChangeImageLibraryCardLimit"];
  onChangeLibraryReferenceCount:
    ChatPageGptPanelCompositionArgs["settings"]["onChangeLibraryReferenceCount"];
  libraryStorageMB: ChatPageGptPanelCompositionArgs["settings"]["libraryStorageMB"];
  libraryReferenceEstimatedTokens:
    ChatPageGptPanelCompositionArgs["settings"]["libraryReferenceEstimatedTokens"];
  googleDriveFolderLink:
    ChatPageGptPanelCompositionArgs["settings"]["googleDriveFolderLink"];
  googleDriveFolderId:
    ChatPageGptPanelCompositionArgs["settings"]["googleDriveFolderId"];
  googleDriveIntegrationMode:
    ChatPageGptPanelCompositionArgs["settings"]["googleDriveIntegrationMode"];
  onChangeGoogleDriveFolderLink:
    ChatPageGptPanelCompositionArgs["settings"]["onChangeGoogleDriveFolderLink"];
  onOpenGoogleDriveFolder:
    ChatPageGptPanelCompositionArgs["settings"]["onOpenGoogleDriveFolder"];
  onImportGoogleDriveFile:
    ChatPageGptPanelCompositionArgs["settings"]["onImportGoogleDriveFile"];
  onIndexGoogleDriveFolder:
    ChatPageGptPanelCompositionArgs["settings"]["onIndexGoogleDriveFolder"];
  onImportGoogleDriveFolder:
    ChatPageGptPanelCompositionArgs["settings"]["onImportGoogleDriveFolder"];
  onShowLibraryItemInChat:
    ChatPageGptPanelCompositionArgs["references"]["onShowLibraryItemInChat"];
  onSendLibraryItemToKin:
    ChatPageGptPanelCompositionArgs["references"]["onSendLibraryItemToKin"];
  onShowAllLibraryItemsInChat:
    ChatPageGptPanelCompositionArgs["references"]["onShowAllLibraryItemsInChat"];
  onSendAllLibraryItemsToKin:
    ChatPageGptPanelCompositionArgs["references"]["onSendAllLibraryItemsToKin"];
  onDownloadLibraryItem:
    ChatPageGptPanelCompositionArgs["references"]["onDownloadLibraryItem"];
  onUploadLibraryItemToGoogleDrive:
    ChatPageGptPanelCompositionArgs["references"]["onUploadLibraryItemToGoogleDrive"];
  onRenderPresentationPlanToPpt:
    ChatPageGptPanelCompositionArgs["references"]["onRenderPresentationPlanToPpt"];
  onImportDeviceImageFile:
    ChatPageGptPanelCompositionArgs["references"]["onImportDeviceImageFile"];
  onImportGoogleDriveImageFile:
    ChatPageGptPanelCompositionArgs["references"]["onImportGoogleDriveImageFile"];
};
