import {
  PRESENTATION_TASK_BASE_CONSTRAINTS,
  PRESENTATION_TASK_DECK_FRAME_CONSTRAINTS,
  PRESENTATION_TASK_FRAME_CONSTRAINTS,
  PRESENTATION_TASK_RENDER_LAYOUT_CONSTRAINTS,
  PRESENTATION_TASK_VISUAL_SLOT_CONSTRAINTS,
  presentationTaskModeConstraint,
} from "@/lib/app/presentation/presentationTaskConstraintSections";

export function buildPresentationTaskConstraints(mode: "create" | "update") {
  return [
    ...PRESENTATION_TASK_BASE_CONSTRAINTS,
    ...PRESENTATION_TASK_DECK_FRAME_CONSTRAINTS,
    ...PRESENTATION_TASK_FRAME_CONSTRAINTS,
    ...PRESENTATION_TASK_VISUAL_SLOT_CONSTRAINTS,
    ...PRESENTATION_TASK_RENDER_LAYOUT_CONSTRAINTS,
    presentationTaskModeConstraint(mode),
  ];
}
