export const GPT_PANEL_TEXT = {
  brand: "ChatGPT",
  currentKinFallback: "Kin未選択",
  chatSettings: "チャット設定",
  taskSettings: "タスク設定",
  librarySettings: "ライブラリ設定",
  loading: "ChatGPTが応答中…",
  injectionSendingPrefix: "注入送信中",
  settingsButton: "設定",
} as const;

export const GPT_TOOLBAR_TEXT = {
  mobileSwitchTitle: "画面切替",
  mobileSwitchButton: "⇄",
  translate: "翻訳",
  replyOnly: "返信のみ",
  polish: "整える",
  sendToKin: "Kinに送る",
  reset: "↻",
  resetTitle: "リセット",
  runTask: "新規タスク",
  updateTask: "更新",
  deepen: "深掘り",
  importResponse: "レス取込",
  attachSearchResult: "検索結果取込",
  sendLatestResponse: "レス共有",
  sendCurrentTask: "タスク共有",
  registerTask: "タスク登録",
  fileImportHint: "ファイル取込は上の「読込」エリアから操作できます。",
  chatTab: "チャット",
  taskPrimaryTab: "タスク1",
  taskSecondaryTab: "タスク2",
  kinTab: "Kin",
  fileTab: "ファイル",
} as const;

export const GPT_COMPOSER_TEXT = {
  target: "対象:",
  uploadKindText: "テキスト",
  uploadKindImagePdf: "画像 / PDF",
  dragActive: "ここにドロップして取込",
  dragIdle: "クリックまたはドラッグ&ドロップで取込",
  ingestButtonTitle: "ファイルを読み込んでタスク整理用の情報を作成",
  selectFileTitle: "ファイルを選択",
  ingesting: "取込中",
  ingest: "取込",
  clearInputTitle: "入力内容をクリア",
  clearInputButton: "×",
  submitTitle: "ChatGPTへ送信",
  sending: "送信中",
  send: "送信",
} as const;

export const GPT_DRAWER_TABS_TEXT = {
  memory: "メモリ",
  tokens: "トークン",
  task: "タスク",
  receivedDocs: "ライブラリ",
} as const;

export const GPT_META_DRAWER_TEXT = {
  runCountSuffix: "回",
  memoryCapacity: "メモリ容量",
  totalPrefix: "合計 ",
  recentMessages: "recentMessages",
  facts: "事実",
  preferences: "好み",
  collections: "コレクション",
  topic: "トピック",
  currentTask: "現在のタスク",
  lastIntent: "直前の意図",
  followUpRule: "フォローアップ規則",
  factsTitle: "事実",
  factsEmpty: "保存された事実はまだありません。",
  preferencesTitle: "好み",
  preferencesEmpty: "保存された好みや要望はまだありません。",
  collectionsTitle: "コレクション",
  collectionsHelp: "検索結果や文書などの補助情報です。",
  collectionsEmpty: "保存されたコレクションはまだありません。",
  memoryInterpretDebug: "Memory Interpret Debug",
  memoryDetail: "メモリ詳細",
  close: "閉じる",
  open: "開く",
  totalTokenUsage: "総トークン使用",
  conversationTokenUsage: "会話トークン使用",
  otherTokenUsage: "その他トークン使用",
  usageMeta: "(合計 / IN / OUT)",
  cumulative: "累計",
  recent1: "直近1回",
  recent5: "直近5回",
  compression: "圧縮",
  search: "検索",
  ingest: "取込",
  task: "タスク",
  image: "画像",
} as const;

export const GPT_TASK_TEXT = {
  drawerTitle: "タスク",
  drawerSubtitle: "タスク形成とタスク進捗をここで切り替えます。",
  draftTab: "タスク形成",
  registrationTab: "タスク登録",
  progressTab: "タスク進捗",
  registration: {
    listTitle: "登録済タスク一覧",
    emptyList: "登録済タスクはまだありません。",
    draftTitle: "SYS_TASK ドラフト",
    libraryTitle: "タスク中ライブラリ参照",
    imageLibraryTitle: "タスク中画像ライブラリ参照",
    libraryEnabled: "ライブラリ参照",
    libraryOn: "オン",
    libraryOff: "オフ",
    libraryCount: "ライブラリ参照件数",
    imageLibraryCount: "画像ライブラリ参照件数",
    recurrenceTitle: "反復設定",
    single: "単発",
    repeat: "反復",
    everyday: "毎日",
    weekdays: ["月", "火", "水", "木", "金", "土", "日"],
    deleteTime: "時間を削除",
    register: "この内容で登録",
    start: "開始",
    edit: "編集",
    delete: "削除",
  },
  editor: {
    title: "タイトル",
    titlePlaceholder: "タスクの主題",
    instruction: "タスク追加指示",
    instructionPlaceholder: "例: 日本史だけに絞る / 500文字以上 / 箇条書きで",
    body: "AI整理本文",
    bodyPlaceholder: "AI が整理した本文です。手動で修正しても構いません。",
  },
  status: {
    idle: "未準備",
    prepared: "形成済み",
    deepened: "深掘り済み",
    formatted: "Kin送信用",
    unset: "未設定",
    emptyBody: "まだ本文はありません。",
    taskSwitch: "タスク切替",
    moveHint: "左右ボタンで次のタスクへ移動できます。必要ならここで新しい下書きタスクを追加できます。",
    currentTask: "現在のタスク",
    keepingCountPrefix: "保持中: ",
    keepingCountSuffix: "件",
    savedToLibrary: "ライブラリに保存しました",
    save: "保存",
    clear: "Clear",
    state: "状態",
    taskName: "タスク名",
    instruction: "指示",
    searchQuery: "検索語",
    sourceCount: "ソース数",
    latestSource: "最新ソース",
    sourceType: "種別",
    updatedAt: "更新日時",
    kinTransfer: "Kin転送",
    transferReady: "転送準備あり",
    policyEdit: "方針編集",
    edit: "編集",
    close: "閉じる",
    editHint: "タイトルと指示はここで編集できます。必要なら後から元の形にしても構いません。",
    titlePlaceholder: "タスクのタイトル",
    instructionPlaceholder: "例: 日本文学だけに / 400文字以内で",
    clearInstruction: "指示をクリア",
    aiBody: "AI形成本文",
    editBody: "本文を編集",
    bodyPlaceholder: "AI形成本文",
    description: "説明",
    descriptionHasTask:
      "編集した結果はこのタスク表示にただちに反映されます。保存すると、タスク内容を整理した情報ドキュメントとしてライブラリにも残せます。",
    descriptionEmpty:
      "まだタスクは形成されていません。上の入力や検索アクションから形成を始められます。",
  },
  progress: {
    noActiveTask: "まだ進行中の Kin タスクはありません。",
    switchPrefix: "進捗表示",
    clear: "クリア",
    currentTask: "現在のタスク",
    hold: "ホールド中",
    goal: "ゴール",
    latestSummary: "最新要約",
    required: "必須進捗",
    optional: "任意進捗",
    noItems: "項目はありません。",
    edit: "編集",
    completed: "完了",
    target: "対象",
    apply: "適用",
    close: "閉じる",
    userRequests: "ユーザーへの依頼",
    noRequests: "依頼項目はありません。",
    question: "質問",
    materialRequest: "資料依頼",
    requiredShort: "必須",
    optionalShort: "任意",
    answerThis: "この依頼に回答",
    setAck: "確認メッセージをセット",
    syncTitle: "進捗カウント同期",
    syncHelp:
      "現在の進捗カウントと pending request を確認し、SYS メッセージを作成できます。必要ならそのまま Kin に転送します。",
    syncBuild: "進捗カウント形成",
    syncPlaceholder: "ここに進捗用 SYS メッセージを作成できます。",
    setKinDraft: "Kin入力欄へセット",
    missingTaskId: "TASK_ID が無いため、まだ形成できません。",
    suspendTitle: "タスク中断",
    suspendHelp: "このタスクをホールドしたい時に、SUSPENDED の SYS メッセージを作成します。",
    suspendPlaceholder: "例: ユーザーから追加依頼が来るまで保留",
    suspendSet: "タスク中断メッセージをセット",
  },
} as const;

export const GPT_PROTOCOL_DRAWER_TEXT = {
  promptTitle: "常設 Prompt",
  promptHelp:
    "Kindroid の prompt 欄に入れる常設ルールです。ここで整理した内容は必要に応じて編集できます。",
  rulebookTitle: "指示ルールブック",
  rulebookHelp:
    "`SYS_INFO` として Kin に送る指示ルールです。必要に応じて編集し、最新版として使えます。",
  resetDefaults: "既定値に戻す",
  setKinDraft: "Kin送信用にセット",
  sendSysInfo: "SYS_INFO として Kin に送る",
} as const;

export const GPT_LIBRARY_DRAWER_TEXT = {
  actions: {
    toggle: "ライブラリ操作",
    collapse: "閉じる",
    expand: "開く",
    showAll: "画面に一括表示",
    sendAllToKin: "Kinに一括送信",
    pending: "次の実装で有効化します",
    modeLabel: "mode",
    modes: {
      index: "Index",
      summary: "Summary",
      detail: "Summary + Detail",
    },
  },
  typeLabels: {
    search: "検索データ",
    kin_created: "Kin作成文書",
    ingested_file: "取込文書",
  },
  emptyAll: "まだライブラリ項目はありません。",
  refPrefix: "Ref",
  taskSelected: "タスク選択中",
  moveUpTitle: "上へ移動",
  moveDownTitle: "下へ移動",
  deleteTitle: "削除",
  useForTask: "タスクに使う",
  download: "ダウンロード",
  modeOptions: {
    default: "全設定に従う",
    summary_only: "summary only",
    summary_with_excerpt: "summary + excerpt",
  },
  edit: "編集",
  previewTitle: "プレビュー",
  fields: {
    filename: "ファイル名",
    type: "種別",
    summary: "Summary",
    none: "なし",
    taskName: "タスク名",
    taskId: "タスクID",
    kin: "Kin",
    completedAt: "完了日時",
    multipart: "分割",
  },
  askAiModeTitle: "Ask AI Mode",
  askAiContinuePrefix: "AIで続ける",
  importTranscript: "文字起こし取込",
  sendTranscriptToKin: "文字起こしをKinへ転送",
  save: "保存",
  cancel: "キャンセル",
} as const;
